### PR TITLE
Material extras occlusion

### LINKED ISSUE #224: Add colorWrite to material-extras
Needed for occlusion. And maybe a transparentOccluder: true/false that sets colorWrite=false and renderOrder=0.

To create an object that is invisible, but still occludes other objects, we need:
-make sure the invisible object is rendered prior to the object(s) it must occlude (by controlling renderOrder);
-make the occluding object invisible by setting its material's colorWrite property to false.

### PR DESCRIPTION
**Pull request by nampereira**
This sets renderOrder=0 and colorWrite=true in one shot:
{"material-extras":{"transparentOccluder": true}}

Can also be set individually:
{"material-extras":{"colorWrite": false}}
{"material-extras":{"renderOrder": 0}}

Close #224

### CODE REVIEW

**Comment by mwfarb** [comment]
It might be good to set this only one way in messages, then developers won't have to test the kwargs for multiple cases trying to find out if the object is occluded. Unless python and other libraries are planning to generate helper functions.

**Comment by mwfarb** [comment]
Just thinking that when a python developer gets the object from persist database, in order to examine if the object is occluded they have to examine 3 keywords: transparentOccluder, colorWrite, and renderOrder. Rather than just 1 or 2.

**Comment by nampereira** [comment]
The values of colorWrite and renderOrder are updated when you use transparentOccluder, so looking at those should be safe. I'm not sure about how much we should rely on renderOrder to conclude something. I can imagine wanting to play with that to have more than just to layers.

**Comment by mwfarb** [comment]
That makes sense.

**Pull request merged**
